=== kimblanquera/GretaECA/Greta_Test/Ogre/character.dtd
<!ELEMENT CHARACTER (HEADFILES,BODYFILES,HEADPOSITION,FACEPOSITION?,LEFT_EYE,RIGHT_EYE,EYE_SCALE,TEETHS-TONGUE,HAIRPOSITION?,FACE_ACCESSORY*)>

<!ELEMENT HEADFILES EMPTY>
<!ELEMENT BODYFILES EMPTY>
<!ELEMENT HEADPOSITION EMPTY>
<!ELEMENT FACEPOSITION EMPTY>
<!ELEMENT LEFT_EYE EMPTY>
<!ELEMENT RIGHT_EYE EMPTY>
<!ELEMENT EYE_SCALE EMPTY>
<!ELEMENT TEETHS-TONGUE EMPTY>
<!ELEMENT HAIRPOSITION EMPTY>
<!ELEMENT FACE_ACCESSORY EMPTY>

<!ATTLIST HEADFILES vertices		CDATA	#REQUIRED>
<!ATTLIST HEADFILES fdps		CDATA	#REQUIRED>
<!ATTLIST HEADFILES indices		CDATA	#REQUIRED>
<!ATTLIST HEADFILES hair		CDATA	"">
<!ATTLIST HEADFILES texture_file	CDATA	"">
<!ATTLIST HEADFILES eyes_texture	CDATA	"">
<!ATTLIST BODYFILES mesh		CDATA	#REQUIRED>
<!ATTLIST BODYFILES texture_file	CDATA	"">
<!ATTLIST LEFT_EYE x			CDATA	#REQUIRED>
<!ATTLIST LEFT_EYE y			CDATA	#REQUIRED>
<!ATTLIST LEFT_EYE z			CDATA	#REQUIRED>
<!ATTLIST RIGHT_EYE x			CDATA	#REQUIRED>
<!ATTLIST RIGHT_EYE y			CDATA	#REQUIRED>
<!ATTLIST RIGHT_EYE z			CDATA	#REQUIRED>
<!ATTLIST EYE_SCALE	factor		CDATA	#REQUIRED>
<!ATTLIST TEETHS-TONGUE x		CDATA	#REQUIRED>
<!ATTLIST TEETHS-TONGUE y		CDATA	#REQUIRED>
<!ATTLIST TEETHS-TONGUE z		CDATA	#REQUIRED>
<!ATTLIST TEETHS-TONGUE	scale		CDATA	"1">
<!ATTLIST HEADPOSITION	scale		CDATA	"1">
<!ATTLIST HEADPOSITION x		CDATA	#REQUIRED>
<!ATTLIST HEADPOSITION y		CDATA	#REQUIRED>
<!ATTLIST HEADPOSITION z		CDATA	#REQUIRED>
<!ATTLIST HAIRPOSITION	scalex		CDATA	"1">
<!ATTLIST HAIRPOSITION	scaley		CDATA	"1">
<!ATTLIST HAIRPOSITION	scalez		CDATA	"1">
<!ATTLIST HAIRPOSITION x		CDATA	#REQUIRED>
<!ATTLIST HAIRPOSITION y		CDATA	#REQUIRED>
<!ATTLIST HAIRPOSITION z		CDATA	#REQUIRED>
<!ATTLIST HAIRPOSITION pitch		CDATA	"0">
<!ATTLIST FACEPOSITION x		CDATA	"0">
<!ATTLIST FACEPOSITION y		CDATA	"0">
<!ATTLIST FACEPOSITION z		CDATA	"0">
<!ATTLIST FACE_ACCESSORY mesh	CDATA	#REQUIRED>
<!ATTLIST FACE_ACCESSORY x		CDATA	"0">
<!ATTLIST FACE_ACCESSORY y		CDATA	"0">
<!ATTLIST FACE_ACCESSORY z		CDATA	"0">
<!ATTLIST FACE_ACCESSORY scale	CDATA	"1">

=== kimblanquera/GretaECA/Greta_Test/Ogre/greta.xml
<?xml version="1.0"?>
<!DOCTYPE CHARACTER SYSTEM "character.dtd" []>
<CHARACTER>

<HEADFILES vertices="greta_animated.mesh" fdps="heads/vertices/greta_FDPs.txt" indices="heads/vertices/greta_indices.txt" hair="greta_hair.mesh" eyes_texture="green_eye"/>

<BODYFILES mesh="body_woman.mesh" texture_file="body_materials2.bmp"/>

<HEADPOSITION x="0" y="12" z="-1" scale="0.5"/>

<LEFT_EYE x="7.6" y="0" z="11.9"/>
<RIGHT_EYE x="-7.6" y="0" z="11.9"/>
<EYE_SCALE factor="2.75"/>

<TEETHS-TONGUE x="0" y="0.3" z="-0.4" scale="1"/>

<HAIRPOSITION x="0" y="0" z="-4" scalex="52" scaley="60" scalez="60" pitch="-90"/>

</CHARACTER>
