=== kimblanquera/GretaECA/Greta_Test/fd/mfe/dtd/multimodal.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT multimodals (multimodal)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT multimodal (cons|signals)*>
<!ATTLIST multimodal
    emotion CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT signals (signal)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT signal EMPTY>
<!ATTLIST signal
    name CDATA #REQUIRED
    type CDATA #IMPLIED
    id CDATA #REQUIRED
    repetitivity CDATA #REQUIRED
    min_duration CDATA #REQUIRED
    max_duration CDATA #REQUIRED
    occurence CDATA #REQUIRED
    probability_start CDATA #REQUIRED
    probability_end CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cons (con)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT con ( (arg*) )>

<!ATTLIST con
    type (rightinc | included | excludes | preceded | exists | morethan | lessthan | equal | and | or | not) #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT arg ((con*) | EMPTY ) >

<!ATTLIST arg
    type (start|stop) #IMPLIED
    id CDATA #IMPLIED
  >

=== kimblanquera/GretaECA/Greta_Test/fd/mfe/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE multimodals SYSTEM "./dtd/multimodal.dtd">
<multimodals>
  <multimodal emotion="embarrassmentS">
    <signals>
      <signal id="1" name="head=head_down_strong" type="head" repetitivity="0" min_duration="2" max_duration="4" occurence="0.5" probability_start="0.8" probability_end="0.3"/>
      <signal id="2" name="head=head_left_strong" type="head" repetitivity="0" min_duration="5" max_duration="9" occurence="0.5" probability_start="0.1" probability_end="0.8"/>
      <signal id="3" name="gaze=look_down" type="gaze" repetitivity="0" min_duration="2" max_duration="4" occurence="0.5" probability_start="0" probability_end="0"/>
      <signal id="4" name="gaze=look_right_strong" type="gaze" repetitivity="0" min_duration="1" max_duration="2" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="5" name="gaze=look_left_strong" type="gaze" repetitivity="0" min_duration="1" max_duration="2" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="6" name="faceexp=embarrassment_signal_6" type="face" repetitivity="1" min_duration="2" max_duration="3" occurence="0.5" probability_start="0.6" probability_end="0.6"/>
      <signal id="7" name="faceexp=nd_joy" type="face" repetitivity="1" min_duration="2" max_duration="4" occurence="0.5" probability_start="0.6" probability_end="0.6"/>
      <signal id="8" name="faceexp=embarrassment_signal_8" type="face" repetitivity="1" min_duration="2" max_duration="5" occurence="0.5" probability_start="0.6" probability_end="0.6"/>
      <signal id="9" name="faceexp=neutral" type="face" repetitivity="0" min_duration="1" max_duration="2" occurence="0.5" probability_start="0.3" probability_end="0.3"/>
      <signal id="10" name="emotion=embarrassment_signal_10" type="gesture" repetitivity="0" min_duration="3" max_duration="5" occurence="0.5" probability_start="0.6" probability_end="0.6"/>
      <signal id="11" name="embarrassment_signal_11" type="torso" repetitivity="0" min_duration="5" max_duration="7" occurence="0.5" probability_start="0.4" probability_end="0.9"/>
      <signal id="12" name="emotion=panic_fear_signal_7" type="gesture" repetitivity="0" min_duration="3" max_duration="5" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
    </signals>
    <cons>
      <!-- ,,EXCLUDES,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, -->
      <!-- ,,head,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, -->
      <con type="excludes">
        <arg id="1"/>
        <arg id="2"/>
      </con>
      <!-- ,gaze,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, -->
      <con type="excludes">
        <arg id="3"/>
        <arg id="4"/>
      </con>
      <con type="excludes">
        <arg id="3"/>
        <arg id="5"/>
      </con>
      <con type="excludes">
        <arg id="4"/>
        <arg id="5"/>
      </con>
      <!-- ,,face,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, -->
      <con type="excludes">
        <arg id="6"/>
        <arg id="7"/>
      </con>
      <con type="excludes">
        <arg id="6"/>
        <arg id="8"/>
      </con>
      <con type="excludes">
        <arg id="6"/>
        <arg id="9"/>
      </con>
      <con type="excludes">
        <arg id="7"/>
        <arg id="8"/>
      </con>
      <con type="excludes">
        <arg id="7"/>
        <arg id="9"/>
      </con>
      <con type="excludes">
        <arg id="8"/>
        <arg id="9"/>
      </con>
    </cons>
  </multimodal>
  <!-- ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, -->
  <multimodal emotion="tensionS">
    <signals>
      <signal id="1" name="faceexp=tension_signal_1" type="face" repetitivity="1" min_duration="1" max_duration="2" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="2" name="faceexp=tension_signal_2" type="face" repetitivity="1" min_duration="1" max_duration="2" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="3" name="faceexp=tension_signal_3" type="face" repetitivity="1" min_duration="1" max_duration="2" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="4" name="faceexp=tension_signal_4" type="face" repetitivity="1" min_duration="1" max_duration="2" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="5" name="faceexp=tension_signal_5" type="face" repetitivity="1" min_duration="1" max_duration="2" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="6" name="faceexp=tension_signal_6" type="face" repetitivity="1" min_duration="1" max_duration="4" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="7" name="faceexp=tension_signal_7" type="face" repetitivity="1" min_duration="1" max_duration="4" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="8" name="emotion=tension_signal_10" type="gesture" repetitivity="0" min_duration="2" max_duration="4" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
    </signals>
    <cons>
      <!-- ,others,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, -->
      <!-- sequence 1 2 3 -->
      <con type="and">
        <arg>
          <con type="equal">
            <arg id="2" type="start"/>
            <arg id="1" type="stop"/>
          </con>
        </arg>
        <arg>
          <con type="exists">
            <arg id="1"/>
          </con>
        </arg>
      </con>
      <con type="and">
        <arg>
          <con type="equal">
            <arg id="3" type="start"/>
            <arg id="2" type="stop"/>
          </con>
        </arg>
        <arg>
          <con type="exists">
            <arg id="2"/>
          </con>
        </arg>
      </con>
      <!-- sequence 4 5 -->
      <con type="and">
        <arg>
          <con type="equal">
            <arg id="5" type="start"/>
            <arg id="4" type="stop"/>
          </con>
        </arg>
        <arg>
          <con type="exists">
            <arg id="4"/>
          </con>
        </arg>
      </con>
    </cons>
  </multimodal>
  <!-- ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, -->
  <multimodal emotion="joyS">
    <signals>
      <signal id="1" name="faceexp=joy_signal_1" type="face" repetitivity="0" min_duration="1" max_duration="4" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="2" name="joy_signal_2" type="torso" repetitivity="0" min_duration="2" max_duration="5" occurence="0.5" probability_start="0" probability_end="0"/>
      <signal id="3" name="faceexp=joy_signal_3" type="face" repetitivity="0" min_duration="1" max_duration="5" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="4" name="faceexp=joy_signal_4" type="face" repetitivity="0" min_duration="1" max_duration="5" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="5" name="head=nod" type="head" repetitivity="0" min_duration="1" max_duration="2" occurence="0.5" probability_start="0.0" probability_end="0.0"/>
      <signal id="6" name="faceexp=joy_signal_6" type="face" repetitivity="0" min_duration="1" max_duration="4" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="7" name="head=joy_signal_7" type="head" repetitivity="0" min_duration="1" max_duration="2" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="8" name="head=joy_signal_8" type="head" repetitivity="0" min_duration="1" max_duration="2" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="9" name="faceexp=joy_signal_9" type="face" repetitivity="0" min_duration="1" max_duration="4" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="10" name="emotion=joy_signal_10" type="gesture" repetitivity="0" min_duration="2" max_duration="4" occurence="0.5" probability_start="0.9" probability_end="0.2"/>
      <signal id="11" name="emotion=joy_signal_11" type="gesture" repetitivity="0" min_duration="3" max_duration="5" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="12" name="emotion=joy_signal_12" type="gesture" repetitivity="0" min_duration="2" max_duration="5" occurence="0.5" probability_start="0" probability_end="0"/>
      <signal id="13" name="emotion=joy_signal_13" type="gesture" repetitivity="0" min_duration="2" max_duration="5" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="14" name="faceexp=joy_signal_14" type="face" repetitivity="0" min_duration="1" max_duration="4" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="15" name="faceexp=joy_signal_15" type="face" repetitivity="0" min_duration="1" max_duration="4" occurence="0.5" probability_start="0.5" probability_end="0.5"/>
      <signal id="16" name="joy_signal_16" type="torso" repetitivity="0" min_duration="2" max_duration="4" occurence="0.5" probability_start="0" probability_end="0"/>
      <signal id="17" name="joy_signal_17" type="torso" repetitivity="0" min_duration="2" max_duration="4" occurence="0.5" probability_start="0" probability_end="0"/>
      <signal id="18" name="joy_signal_18" type="torso" repetitivity="0" min_duration="2" max_duration="4" occurence="0.5" probability_start="0" probability_end="0"/>
      <signal id="19" name="joy_signal_19" type="torso" repetitivity="0" min_duration="2" max_duration="4" occurence="0.5" probability_start="0" probability_end="0"/>
